version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: x64
image: Visual Studio 2019
clone_folder: c:\OpenGL_Examples
install:
- ps: git submodule update -q --init --recursive
before_build:
- ps: >-
    md build

    cd build

    cmake -G "Visual Studio 16 2019" ..
build:
  project: c:\OpenGL_Examples\build\OpenGL_Examples.sln
  parallel: true
  verbosity: normal
